CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`usuario_BEFORE_UPDATE` BEFORE UPDATE ON `usuario` FOR EACH ROW
BEGIN
   IF (NEW.CPF IS NULL AND NEW.CNPJ IS NULL)
      OR (NEW.CPF IS NOT NULL AND NEW.CNPJ IS NOT NULL) THEN
      SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'Informe apenas CPF ou CNPJ (nunca ambos ou nenhum).';
   END IF;
END;
